config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "patients#index"

  resources :patients
  resources :charts
  resources :doctors

 get '/sign_in', to: 'users#sign_in'
 post '/sign_in', to: 'users#sign_in!'
 get '/sign_up', to: 'users#sign_up'
 post '/sign_up', to: 'users#sign_up!'
 get '/sign_out', to: 'users#sign_out'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chart.rb
class Chart < ApplicationRecord
  belongs_to :patient
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_and_belongs_to_many :patients, inverse_of: :doctors
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :charts, dependent: :destroy
  belongs_to :user
  has_and_belongs_to_many :doctors, inverse_of: :patients
  before_destroy { doctors.clear }
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true
  has_secure_password
  has_many :patients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate

  private
  def authenticate
    if !session[:user]
      redirect_to "/sign_in"
    end
  end
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  def show
    @chart = Chart.find(params[:chart_id])
    @patients = Patient.find(params[:id])
  end

  def new
    @patients = Patient.find(params[:patient_id])
    @charts = Chart.new
  end

  def create
      patient= Patient.find(params[:chart][:patient_id])
      Chart.create(chart_params)

      redirect_to patient
    end
  def edit
      @charts = Chart.find(params[:chart_id])
      @patients = Patient.find(params[:id])
  end
  def update
    chart = Chart.find(params[:id])
    chart.update(chart_params)
    patient = Patient.find(params[:chart][:patient_id])
    redirect_to patient
  end
  private
  def chart_params
      params.require(:chart).permit(:date, :pre_breath, :pre_swelling, :accident_since_last_treatment, :change_mobility, :pre_digestion_problems, :access_in_place, :blood_flow_rate, :post_breath, :post_swelling, :post_digestion_problems, :bruising, :total_time, :missed_treatment, :patient_id)
  end

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

  def index
    @doctors = Doctor.all
  end

  def show
      @doctors = Doctor.find(params[:id])
  end

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.new(doctor_params)
    if @doctor.save
      redirect_to '/doctors'
    else
      redirect_to '/doctors/new'
    end
  end

  def edit
    @doctor = Doctor.find(params[:id])
  end

  def update
    doctor = Doctor.find(params[:id])
    doctor.update(doctor_params)

    redirect_to doctor
  end

  def destroy
    doctor = Doctor.find(params[:id])
    doctor.destroy

   redirect_to doctors_path
end
  private
  def doctor_params
    params.require(:doctor).permit(:name, :phone_number, :email, :specialty )
  end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def index
    @patients = User.find(session[:user]["id"]).patients
  end

  def show
      @patients = Patient.find(params[:id])
  end

  def new
    @patient = Patient.new
  end

  def create
    @user = User.find(session[:user]["id"])
    @patient = @user.patients.create!(patient_params)
    redirect_to @patient
  end

  def edit
    @patient = Patient.find(params[:id])
  end

  def update
    patient = Patient.find(params[:id])
    patient.update(patient_params)

    redirect_to patient
  end

  def destroy
    patient = Patient.find(params[:id])
    patient.destroy

   redirect_to patients_path
end
  private
  def patient_params
    params.require(:patient).permit(:name, :age, :height, :weight, :email, :phone_number)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate
  def sign_up
  end

  def sign_up!
    user = User.new(
      username: params[:username],
      password_digest: BCrypt::Password.create(params[:password])
    )
    if params[:password_confirmation] != params[:password]
      message = "Your passwords don't match!"
    elsif user.save
      message = "Your account has been created!"
    else
      message = "Your account couldn't be created. Did you enter a unique username and password?"
    end
    flash[:notice] = message
    redirect_to action: :sign_up
  end

  def sign_in
  end

  def sign_in!
    @user = User.find_by(username: params[:username])
    if !@user
      message = "This user doesn't exist!"
    elsif !BCrypt::Password.new(@user.password_digest).is_password?(params[:password])
      message = "Your password's wrong!"
    else
      message = "You're signed in, #{@user.username}!"
      cookies[:username] = {
      value: @user.username,
      expires: 100.years.from_now
    }
    session[:user] = @user
    end
    flash[:notice] = message
    redirect_to patients_path
  end

  def sign_out
    reset_session
    flash[:notice] = "You're signed out!"
    redirect_to root_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/charts/_form.html.erb
<%= form_for @charts do |f| %>
<%= f.hidden_field :patient_id, :value => @patients.id %>
<div class ="font">
<div class="input-field col s6" class="card-panel" >
    <%= f.label :date %>
    <%= f.text_field :date %>
</div>
<div class="input-field col s6">
    <%= f.label :breathing_issues %>
    <%= f.text_field :pre_breath %>
</div>
<div class="input-field col s6">
    <%= f.label :swelling_issues %>
    <%= f.text_field :pre_swelling %>
</div>
<div class="input-field col s6">
    <%= f.label :accident_since_last_treatment %>
    <%= f.text_field :accident_since_last_treatment %>
</div>
<div class="input-field col s6">
    <%= f.label :change_in_mobility %>
    <%= f.text_field :change_mobility %>
</div>
<div class="input-field col s6">
    <%= f.label :any_pre_digestion_problems %>
    <%= f.text_field :pre_digestion_problems %>
</div>
<div class="input-field col s6">
    <%= f.label :blood_flow_rate %>
    <%= f.number_field :blood_flow_rate %>
</div>
<div class="input-field col s6">
    <%= f.label :post_breathing_issues %>
    <%= f.text_field :post_breath %>
</div>
<div>
  <div class="input-field col s6">
    <%= f.label :post_swelling_issues %>
    <%= f.text_field :post_swelling %>
</div>
<div>
  <div class="input-field col s6">
    <%= f.label :any_post_digestion_problems %>
    <%= f.text_field :post_digestion_problems %>
</div>
<div>
  <div class="input-field col s6">
    <%= f.label :any_bruising %>
    <%= f.text_field :bruising %>
</div>
<div>
  <div class="input-field col s6">
    <%= f.label :total_time %>
    <%= f.text_field :total_time %>
</div>
<div>
  <div class="input-field col s6">
    <%= f.label :missed_treatment %>
    <%= f.text_area :missed_treatment %>
</div>
<div/>
<%= f.submit "Submit", :class => "btn waves-effect waves-light" %>
<% end %>

app/views/charts/edit.html.erb
<h1>Edit Chart</h1>

<%= render 'charts/form' %>

app/views/charts/new.html.erb
<h2>New Chart </h2>


<%= render 'charts/form' %>

app/views/charts/show.html.erb
<h1><%= @patients.name %></h1>
<h1><%= @chart.date %></h1>



<div id="show_chart">
    <p>Pre-Breathing: <%= @chart.pre_breath %></p>
    <p>Pre-Swelling: <%= @chart.pre_swelling %></p>
    <p>Previous Accidents: <%= @chart.accident_since_last_treatment %></p>
    <p>Mobility: <%= @chart.change_mobility %></p>
    <p>Pre-Digestive Problems: <%= @chart.pre_digestion_problems %></p>
    <p>Blood Flow Rate:<%= @chart.blood_flow_rate %></p>
    <p>Post Breath: <%= @chart.post_breath %></p>
    <p>Post Swelling: <%= @chart.post_swelling %></p>
    <p>Post-Digestive Problems: <%= @chart.post_digestion_problems %></p>
    <p>Bruising: <%= @chart.bruising %></p>
    <p>Total Time: <%= @chart.total_time %></p>
    <p>Missed Treatment: <%= @chart.missed_treatment %></p>
</div>

<h4><%= link_to "Back to Patient", patient_path %></h4>

app/views/doctors/_form.html.erb
<%= form_for @doctor do |f| %>
  <div>
    <%= f.label :name%>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :phone %>
    <%= f.text_field :phone_number %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :specialty %>
    <%= f.text_field :specialty %>
  </div>
  <%= f.submit "Submit" %>
<% end %>

app/views/doctors/edit.html.erb
<h1>Edit Doctor Information</h1>

<%= render 'doctors/form' %>

app/views/doctors/index.html.erb
<h1>Clinic Doctors</h1>

<h3><%= link_to "Add a Doctor", new_doctor_path %></h2>

<table style="width:50%">
  <tr>
    <th>Name</th>
    <th>Phone #</th>
    <th>Email</th>
    <th>Specialize</th>

  </tr>

  <% @doctors.each do |doc| %>
    <tr>
      <!-- <td><%# link_to doc.name, doctor %></td> -->
      <td><%= link_to doc.name, doc %></td>
      <td><%= doc.phone_number %></td>
      <td><%= doc.email %></td>
      <td><%= doc.specialty %></td>
    </tr>
  <% end %>
</table>

app/views/doctors/new.html.erb
<h1>Add a Physician</h1>

<%= render 'doctors/form' %>

app/views/doctors/show.html.erb
<h1> Doctor</h1>



<h2><%= @doctors.name %></h2>

<p>Phone #: <%= @doctors.phone_number %></p>
<p>Email: <%= @doctors.email %></p>
<p>Specialty: <%= @doctors.specialty %></p>

<%= link_to "Back to all Doctors", doctors_path %><br>
<%= link_to "Edit Doctor", edit_doctor_path(@doctors) %>
<br>
<%= link_to "Delete", doctor_path(@doctors), method: :delete, data: { confirm: 'Are you sure?' }
%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dialysis</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>HomeDialysis</h1>
    <nav class="blue darken-4">
      <% if session[:user] %>
        <h4><a href="/sign_out"><%= session[:user]["username"] %>: sign out</a></h4>
      <% else %>
        <a href="/sign_up">Sign up</a>
        <a href="/sign_in">Sign in</a>
      <% end %>
    </nav>
    <br>
    <em><%= flash[:notice] %></em>
    <%= yield %>
  </body>
</html>

app/views/patients/_form.html.erb
<%= form_for @patient do |f| %>
  <div>
    <%= f.label :name%>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :age %>
    <%= f.text_area :age %>
  </div>
  <div>
    <%= f.label :height %>
    <%= f.text_area :height %>
  </div>
  <div>
    <%= f.label :weight %>
    <%= f.text_area :weight %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_area :email %>
  </div>
  <div>
    <%= f.label :phone_number %>
    <%= f.text_area :phone_number %>
  </div>
  <%= f.submit "Submit" %>
<% end %>

app/views/patients/edit.html.erb
<h1>Edit Patient</h1>

<%= render 'patients/form' %>

app/views/patients/index.html.erb
<h1>Patients</h1>

<img src="<%# asset_path( 'hospital-word.jpg' ) %>" />
<h4><%= link_to "New Patient", new_patient_path %></h4>

<table style="width:50%" style="overflow-x:auto;" class= "table table-bordered">
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th>Height</th>
    <th>Weight</th>
    <th>Email</th>
    <th>Phone#</th>
  </tr>

  <% @patients.each do |patient| %>
    <tr>
      <td><%= link_to patient.name, patient %></td>
      <td><%= patient.age %></td>
      <td><%= patient.height %></td>
      <td><%= patient.weight %></td>
      <td><%= patient.email %></td>
      <td><%= patient.phone_number %></td>
    </tr>
  <% end %>
</table>

app/views/patients/new.html.erb
<h1>Create your Profile</h1>

<%= render 'patients/form' %>

app/views/patients/show.html.erb
<h2><%= @patients.name %></h2>
<div style = "text-align:center; border:2px solid black;">
<p><h5>Age: </h5><%= @patients.height%>ft</p>
<p><h5>Weight: </h5><%= @patients.weight%> lbs</p>
<p><h5>Email: </h5><%= @patients.email%></p>
<p><h5>Phone#: </h5><%= @patients.phone_number%></p>
</div>
<%= link_to "Back to all Patients", patients_path %><br>
<%= link_to "Edit Patient", edit_patient_path(@patients) %>
<br>
<%= link_to "Delete", patient_path(@patients), method: :delete, data: { confirm: 'Are you sure?' }
%>

<br>
<h3>Charts</h3>
<%= link_to "New Chart", new_chart_path(:patient_id => @patients.id) %>

<table style="width:50%" style="overflow-x:auto;" class= "table table-bordered">
  <tr>
    <th>Date</th>
    <th>Pre-Breathing</th>
    <th>Pre-Swelling</th>
    <th>Previous Accidents</th>
    <th>Mobility</th>
    <th>Pre-Digestive Problems</th>
    <th>Blood Flow Rate</th>
    <th>Post Breath</th>
    <th>Post Swelling</th>
    <th>Post-Digestive Problems</th>
    <th>Bruising</th>
    <th>Total Time</th>
    <th>Missed Treatment</th>
  </tr>

  <% @patients.charts.each do |chart| %>
    <tr>
      <td><%= chart.date %></td>
      <td><%= chart.pre_breath %></td>
      <td><%= chart.pre_swelling %></td>
      <td><%= chart.accident_since_last_treatment %></td>
      <td><%= chart.change_mobility %></td>
      <td><%= chart.pre_digestion_problems %></td>
      <td><%= chart.blood_flow_rate %></td>
      <td><%= chart.post_breath %></td>
      <td><%= chart.post_swelling %></td>
      <td><%= chart.post_digestion_problems %></td>
      <td><%= chart.bruising %></td>
      <td><%= chart.total_time %></td>
      <td><%= chart.missed_treatment %></td>
      <td><%= link_to "View", chart_path(:chart_id => chart.id) %></td>
      <td><%= link_to "Edit", edit_chart_path(:chart_id => chart.id) %></td>
    </tr>
  <% end %>
</table>

app/views/users/sign_in.html.erb
<h2>Sign in</h2>
<%= form_tag("/sign_in", method: "post") do %>
  <input type="text" name="username" placeholder="username" />
  <input type="password" name="password" placeholder="password" />
  <input type="submit" value="Sign in" />
<% end %>

app/views/users/sign_up.html.erb
<h2>Sign up</h2>
<%= form_tag("/sign_up", method: "post") do %>
  <input type="text" name="username" placeholder="username" />
  <input type="password" name="password" placeholder="password" />
  <input type="password" name="password_confirmation" placeholder="password again" />
  <input type="submit" value="Sign up" />
<% end %>